services:
  redis:
    replicas: 1
    image: redis:6.2-alpine
    ports:
      - "6379"
    volumes:
      - "/var/lib/redis"
      - "/usr/local/etc/redis/redis.conf"

  web:
    public: true
    replicas: 1
    environment:
      - PRODUCTION_DATABASE=$COMMUNITY_PRODUCTION_DATABASE
      - DEVELOPMENT_DATABASE=$COMMUNITY_DEVELOPMENT_DATABASE
      - DATABASE_PASSWORD=$COMMUNITY_DATABASE_PASSWORD
      - DATABASE_USERNAME=$COMMUNITY_DATABASE_USERNAME
      - DATABASE_HOST=$COMMUNITY_DATABASE_HOST
      - DATABASE_PORT=$COMMUNITY_DATABASE_PORT
      - STORAGE_AWS_ACCESS_KEY_ID=$COMMUNITY_PRODUCTION_STORAGE_AWS_ACCESS_KEY_ID
      - STORAGE_SECRET_ACCESS_KEY=$COMMUNITY_PRODUCTION_STORAGE_SECRET_ACCESS_KEY
      - STORAGE_AWS_REGION=$COMMUNITY_PRODUCTION_STORAGE_AWS_REGION
      - STORAGE_AWS_S3_BUCKET_NAME=$COMMUNITY_PRODUCTION_STORAGE_AWS_S3_BUCKET_NAME
      - STORAGE_AWS_ENDPOINT=$COMMUNITY_PRODUCTION_STORAGE_AWS_ENDPOINT
      - ADMIN_PASSWORD=$COMMUNITY_ADMIN_PASSWORD
      - ADMIN_EMAIL=$COMMUNITY_ADMIN_EMAIL
      - REDIS_URL=redis://redis:6379/1
      - MEMCACHE_SERVERS=cache:11211
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - SECRET_KEY_BASE=$COMMUNITY_SECRET_KEY_BASE
    image: registry.cloud.okteto.net/community-drakkarsoftware/community:latest
    ports:
      - "3000"

  worker:
    replicas: 2
    environment:
      - PRODUCTION_DATABASE=$COMMUNITY_PRODUCTION_DATABASE
      - DEVELOPMENT_DATABASE=$COMMUNITY_DEVELOPMENT_DATABASE
      - DATABASE_PASSWORD=$COMMUNITY_DATABASE_PASSWORD
      - DATABASE_USERNAME=$COMMUNITY_DATABASE_USERNAME
      - DATABASE_HOST=$COMMUNITY_DATABASE_HOST
      - DATABASE_PORT=$COMMUNITY_DATABASE_PORT
      - STORAGE_AWS_ACCESS_KEY_ID=$COMMUNITY_PRODUCTION_STORAGE_AWS_ACCESS_KEY_ID
      - STORAGE_SECRET_ACCESS_KEY=$COMMUNITY_PRODUCTION_STORAGE_SECRET_ACCESS_KEY
      - STORAGE_AWS_REGION=$COMMUNITY_PRODUCTION_STORAGE_AWS_REGION
      - STORAGE_AWS_S3_BUCKET_NAME=$COMMUNITY_PRODUCTION_STORAGE_AWS_S3_BUCKET_NAME
      - STORAGE_AWS_ENDPOINT=$COMMUNITY_PRODUCTION_STORAGE_AWS_ENDPOINT
      - REDIS_URL=redis://redis:6379/1
      - MEMCACHE_SERVERS=cache:11211
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - SECRET_KEY_BASE=$COMMUNITY_SECRET_KEY_BASE
    image: registry.cloud.okteto.net/community-drakkarsoftware/community:latest
    command: bundle exec sidekiq -C config/sidekiq.yml

  cache:
    replicas: 1
    image: memcached:1.6.15-alpine
    resources:
      cpu: 1
      memory: 2Gi
