version: '3.7'

services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env.prod
    expose:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.prod
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - "./redis-data:/var/lib/redis"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"

  api:
    image: herklos/community2:latest-backend
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.test-community.rule=Host(`test-community.octobot.online`)"
      - "traefik.http.routers.test-community.entrypoints=websecure"
      - "traefik.http.routers.test-community.tls=true"
    env_file:
      - .env.prod
    expose:
      - "3000"
    restart: always
    depends_on:
      - "db"
      - "redis"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - gateway

  cache:
    image: memcached:1.6.12-alpine

networks:
  gateway:
    external:
      name: gateway
