services:
  db:
    replicas: 1
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=82Cv3ZoT6vt!tyTQQ
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=0.0.0.0
    ports:
      - "5432"
    volumes:
      - "/var/lib/postgresql/data"

  redis:
    replicas: 1
    image: redis:6.2-alpine
    ports:
      - "6379"
    volumes:
      - "/var/lib/redis"
      - "/usr/local/etc/redis/redis.conf"

  web:
    public: true
    replicas: 1
    environment:
      - PRODUCTION_DATABASE=production
      - DATABASE_PASSWORD=82Cv3ZoT6vt!tyTQQ
      - DATABASE_USERNAME=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - STORAGE_AWS_ACCESS_KEY_ID=SCW5VNDZGVPQWT0SXY6M
      - STORAGE_SECRET_ACCESS_KEY=880311b3-87fa-4dac-8011-95d06a2c3c6b
      - STORAGE_AWS_REGION=nl-ams
      - STORAGE_AWS_S3_BUCKET_NAME=community-assets
      - STORAGE_AWS_ENDPOINT=https://s3.nl-ams.scw.cloud
      - ADMIN_PASSWORD=AZ1cza2e14azdaMMSDKZ121z
      - ADMIN_EMAIL=spree@example.com
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - SECRET_KEY_BASE=DZe1a5e6az1dq2s3c1q
    image: registry.cloud.okteto.net/staging-community-drakkarsoftware/community:latest
    ports:
      - "3000"

#  worker:
#    replicas: 1
#    environment:
#      - PRODUCTION_DATABASE=production
#      - DATABASE_PASSWORD=82Cv3ZoT6vt!tyTQQ
#      - DATABASE_USERNAME=postgres
#      - DATABASE_HOST=db
#      - DATABASE_PORT=5432
#      - STORAGE_AWS_ACCESS_KEY_ID=SCW5VNDZGVPQWT0SXY6M
#      - STORAGE_SECRET_ACCESS_KEY=880311b3-87fa-4dac-8011-95d06a2c3c6b
#      - STORAGE_AWS_REGION=nl-ams
#      - STORAGE_AWS_S3_BUCKET_NAME=community-assets
#      - STORAGE_AWS_ENDPOINT=https://s3.nl-ams.scw.cloud
#      - ADMIN_PASSWORD=AZ1cza2e14azdaMMSDKZ121z
#      - REDIS_URL=redis://redis:6379/1
#      - RAILS_ENV=production
#      - RAILS_MAX_THREADS=5
#      - SECRET_KEY_BASE=DZe1a5e6az1dq2s3c1q
#    image: registry.cloud.okteto.net/community-drakkarsoftware/community:1.0.1
#    command: bundle exec sidekiq -C config/sidekiq.yml