version: '3.4'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    image: postgres:11-alpine
    expose:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:5.0.13-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  app:
    image: octobotservers/community:${IMAGE_TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.test-community.rule=Host(`test-community.octobot.online`)"
      - "traefik.http.routers.test-community.entrypoints=websecure"
      - "traefik.http.routers.test-community.tls=true"
    environment:
      - PRODUCTION_DATABASE=${PRODUCTION_DATABASE}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_CANDLES_BUCKET_NAME=${S3_CANDLES_BUCKET_NAME}
      - TENTACLE_SERVER_URL=${TENTACLE_SERVER_URL}
      - HOST_DOMAIN=${HOST_DOMAIN}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    links:
      - db
    expose:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

  cache:
    image: memcached:1.6.10-alpine

networks:
  default:
    external:
      name: gateway
