version: '3.7'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  redis:
    image: redis:6.2-alpine
    env_file:
      - .env.dev
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/var/lib/redis"
      - "./data/redis.conf:/usr/local/etc/redis/redis.conf"

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: sh -c "rm -rf tmp/pids/server.pid && rails db:migrate && bundle exec rails s -b 0.0.0.0 -p 4000"
    env_file:
      - .env.dev
    ports:
      - "4000:4000"
    volumes:
      - ".:/app"
    depends_on:
      - "db"
      - "redis"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - .env.dev
    volumes:
      - ".:/app"
    depends_on:
      - "db"
      - "redis"

volumes:
  postgres-data:
