---
:concurrency: 5
:queues:
  - default
  - mailers
  - active_storage_analysis
  - spree_webhooks

:schedule:
#  hosting_refresh_deployments_job:
#    cron: '0 * * * * *'   # Runs once per minute
#    class: Spree::Hosting::HostingRefreshDeploymentsJob
  subscription_job:
    cron: '0 * * * *'  # Runs once per minute
    class: Spree::SubscriptionJob
  purge_storage_job:
    cron: '0 5 * * *'  # Runs once per day at 05:00
    class: PurgeStorageJob
