default:
  navigation:
    - title: Tentacles Packages
      subtitle: Categories
      url: /t/tentacles-packages
      items:
        - :title: Officials
          :url: /t/tentacles-packages/officials
        - :title: Community
          :url: /t/tentacles-packages/community
      promo_banners:
        - subtitle: 'New tentacles packages : websockets'
          title: Websockets are now available
          url: /t/tentacles-packages/websockets
          image: ''
    - title: Cloud
      subtitle: Categories
      url: /t/cloud
      items:
        - :title: OctoBot Hosting
          :url: /t/cloud/hosting
        - :title: Backtesting
          :url: /t/cloud/backtesting
