name: Community - Docker
on: [ push ]

jobs:
  lint:
    name: ubuntu-latest - Docker - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          hadolint_ignore: DL3013 DL3008

  build_and_push:
    name: ubuntu-latest - Docker - build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          OWNER=octobotservers
          IMG=community
          SUFFIX=backend
          echo "VERSION=${GITHUB_REF##*/}-${SUFFIX}" >> $GITHUB_ENV
          echo "IMAGE=${OWNER}/${IMG}" >> $GITHUB_ENV
          echo "LATEST=latest-${SUFFIX}" >> $GITHUB_ENV
          echo "DEV=dev-${SUFFIX}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.production
          platforms: linux/amd64
          push: false
          tags: ${{ env.IMAGE }}:${{ env.LATEST }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push dev
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags') && github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE }}:${{ env.DEV }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push latest
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE }}:${{ env.LATEST }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push on tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.LATEST }}
            ${{ env.IMAGE }}:${{ env.VERSION }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  okteto_build:
    name: ubuntu-latest - Okteto build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: okteto/login@2.1.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Build staging
        uses: okteto/build@1.15.8
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          file: Dockerfile.development
          tag: registry.cloud.okteto.net/staging-community-drakkarsoftware/community:latest
          buildargs: GITHUB_TOKEN

      - name: Build production
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master')
        uses: okteto/build@1.15.8
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          file: Dockerfile.development
          tag: registry.cloud.okteto.net/community-drakkarsoftware/community:latest
          buildargs: GITHUB_TOKEN

  okteto_deploy_staging:
#    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master')
    name: ubuntu-latest - Docker - Deploy - Staging
    runs-on: ubuntu-latest
    needs:
      - lint
      - okteto_build
    steps:
      - uses: actions/checkout@v2

      - uses: okteto/login@2.1.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@2.1.0
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: staging-community-drakkarsoftware

      - name: Deploy
        uses: okteto/deploy-stack@2.1.0
        with:
          name: okteto-staging-community
          namespace: staging-community-drakkarsoftware
          file: docker-compose.staging.okteto.yml
          build: false

  okteto_deploy_production:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master')
    name: ubuntu-latest - Docker - Deploy - Production
    runs-on: ubuntu-latest
    needs:
      - lint
      - okteto_build
      - okteto_deploy_staging
    steps:
      - uses: actions/checkout@v2

      - uses: okteto/login@2.1.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@2.1.0
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: community-drakkarsoftware

      - name: Deploy
        uses: okteto/deploy-stack@2.1.0
        with:
          name: okteto-community
          namespace: community-drakkarsoftware
          file: docker-compose.okteto.yml
          build: false

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - lint
      - build_and_push
      - okteto_build
      - okteto_deploy_staging
      - okteto_deploy_production
    if: ${{ failure() }}

    steps:
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          status: Failure
          webhook: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
